name: Deploy to Custom Server

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Adjust this to your PHP version
          tools: composer

      # Step 3: Install PHP dependencies
      - name: Install Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Step 4: Deploy via SSH
      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

          # Sync files to the server and exclude sensitive files
          rsync -avz --delete \
            --include='/public/***' \
            --include='/src/***' \
            --include='/vendor/***' \
            --include='/sql/***' \
            --exclude='.htaccess' \
            --exclude='*.sqlite' \
            ./ "$SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH"