name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3, 8.4]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use PHP ${{ matrix.node-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.node-version }}
    
    - run: composer i
    
    - run: composer run test

    - run: mkdir ./build
    - run: cp -r ./public ./build/public
    - run: cp -r ./src ./build/src
    - run: cp -r ./vendor ./build/vendor
    - run: cp ./.github/apache/.htaccess ./build/.htaccess

    - run: ls -la ./build
    
#    - name: Upload ftp
#      uses: sebastianpopp/ftp-action@releases/v2
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#        user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "build"
#        remoteDir: "public_html"
#        options: "--delete --asci"